### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by kei-sukey** [kei-sukey/protospace-32584#1]
# URL
https://protospace-32584.herokuapp.com/

**Comment by Nishi0418** [comment]
山井さん
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
proto編集機能
- protoに空欄を作り、保存する
- 上記をした後に、全ての項目を入力し、保存を押すとスクリーンショットのエラーが発生します。
<img width="1440" alt="スクリーンショット 2020-12-10 21 22 46" src="https://user-images.githubusercontent.com/51874745/101771976-157d4e00-3b2e-11eb-9746-48fa969193e2.png">


修正し次第、以下のprotospace完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by kei-sukey** [comment]
レビューありがとうございます！修正箇所について、修正実施致しました。
protospace完了報告フォームを再提出させて頂きますので、ご確認お願い致します！

**Comment by Nishi0418** [comment]
山井さん
ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

別途、最終課題の案内をチャンネルの方に送信させて頂きます。
今しばらくお待ちください。
